TEST_DAYS: 90
WINDOW_SIZE: 21
THRESHOLD: 2
SEQ_SIZE: 21
BATCH_SIZE: 32
D_MODEL: 64
N_HEAD: 4
NUM_LAYERS: 2
DROPOUT: 0.1
LEARN_RATE: 0.0001
NUM_EPOCHS: 80
DECAY_RATE: 0.1
PLOT_ANOMALIES: false
SHOW_BOUNDS: false